resources:
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: mvn_example_build
      buildNumber: 1
      
  - name:       Git2
    type:       GitRepo
    configuration:
      gitProvider:  github-disha
      repository:   github-disha
      path:         dishameswania/project-examples
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
      - name: try2
        type: MvnBuild
        configuration:
          #inherits from bash
          sourceLocation:   artifactory-maven-plugin-example      # required
          mvnCommand:       clean install -f ./pom.xml      # required
          configFileLocation:   .      # required
          configFileName:   mvn-art-config      # required
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
         
          integrations:
            - name:         artdisha
          inputResources:
            - name:         Git2         # required
 
        execution:
          onStart:
            - echo "Starting execution"
            - javac -v
          
      - name: publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: try2
          outputResources:
            - name: build_info
