resources:
  - name:       Git1
    type:       GitRepo
    configuration:
      gitProvider:  github-disha
      repository:   github-disha
      path:         dishameswania/ArtifactoryTest
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
    - name: try1
      type: Bash
            
      execution:
          onExecute:
            - echo "Executing step 1"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job."
