resources:
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: mvn_example_build
      buildNumber: 1
      
  - name:       Git2
    type:       GitRepo
    configuration:
      gitProvider:  git-disha
      repository:   git-disha
      path:         dishameswania/project-examples
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
      - name: try2
        type: MvnBuild
        configuration:
          #inherits from bash
          sourceLocation:   artifactory-maven-plugin-example      # required
          mvnCommand:       clean install -f ./pom.xml      # required
          configFileLocation:   .      # required
          configFileName:   mvnArtConfig      # required
          
          integrations:
            - name:         artdisha
          inputResources:
            - name:         Git2         # required
 
        execution:
          onStart:
            - echo "Preparing for work..."
            - apt install default-jdk
            - pushd /tmp
            - wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
            - tar xzvf apache-maven-3.6.1-bin.tar.gz
            - export PATH=$PATH:/tmp/apache-maven-3.6.1/bin
            - export M2_HOME=/tmp/apache-maven-3.6.1/
            - popd
            - javac -version
            - mvn --version
      - name: publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: try2
          outputResources:
            - name: build_info
