resources:
  - name:       Git2
    type:       GitRepo
    configuration:
      gitProvider:  git-disha
      repository:   git-disha
      path:         dishameswania/project-examples
    buildOn:
      commit: true     

pipelines:
  - name: pipe1
    steps:
      - name: try2
        type: MvnBuild
        configuration:
          #inherits from bash
          mvnCommand:       mvn clean      # required
          sourceLocation:   maven-example      # required
          configFileLocation:   maven-example      # required
          configFileName:   pom.xml      # required

          inputResources:
            - name:         Git2         # required
 
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                  #always
            - echo "Cleaning up some stuff"
